### ISSUE TITLE
Logo Design For Currency Converter

### ISSUE THREAD

**Issue by zularizal** [Apilytic/currency-converter#28]
Hi @gogoluxecs , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by gogoluxecs** [comment]
hi @zularizal and thank you. Im curries to check what you have in mind.

**Comment by zularizal** [comment]
Wait a minute, I will design some sample logos for you.

**Comment by gogoluxecs** [comment]
hey thank you all of them looking very nice I like the green one :)

**Comment by zularizal** [comment]
Hi @gogoluxecs  , I already uploaded the logo to drive

https://drive.google.com/open?id=1iQ3nnFapkIci5i2IeSRI1G-RiVbmJFGt

And also I have sent a pull request for you. #29

**Comment by gogoluxecs** [comment]
@zularizal merged. Thanks a lot!
